### ISSUE TITLE
Benchmark critical sections of signature verification

### ISSUE THREAD

**Issue by PaddyMc** [allinbits/cosmos-cash#97]
As an issuer, we sign a credential using our issuer key,

The method we follow needs to be updated to instead of signing a piece of data we sign the hash of that data instead.

This also needs to be benchmarked so we can reason about improvement to the flow.

**Comment by noandrea** [comment]
Two signing/verification strategies are compared sign/verification:
- directly on the verifiable credential data
- on the hash (blake2b) of the verifiable credential data 

then 2 simple scenarios are tested:
- legit verifiable credential message
- malicious verifiable credential message where the subject's root field contains a lot of data

Assumptions: 
the assumption is that sign/verify hashes of the data (instead of the data itself) may be significantly less expensive and therefore making the node more resilient to ddos attacks 

Input data: https://gist.github.com/noandrea/dcaaeca5361ca2a2631759b47a78ba6b

Benchmark results:
```
➜ go test -run=Sig   -bench=. ./helpers
goos: linux
goarch: amd64
pkg: github.com/allinbits/cosmos-cash/helpers
cpu: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
BenchmarkSignatureSignCredential-8                	    8492	    140666 ns/op
BenchmarkSignatureSignCredentialHash-8            	    8403	    148348 ns/op
BenchmarkSignature-8                              	    3390	    346645 ns/op
BenchmarkSignatureHash-8                          	    3406	    344804 ns/op
BenchmarkSignatureSignCredentialMalicious-8       	     237	   4946688 ns/op
BenchmarkSignatureSignCredentialHashMalicious-8   	     495	   2239557 ns/op
BenchmarkSignatureMalicious-8                     	     122	   9641632 ns/op
BenchmarkSignatureHashMalicious-8                 	     258	   4468095 ns/op
PASS
ok  	github.com/allinbits/cosmos-cash/helpers	11.768s
```

**Comment by noandrea** [comment]
open questions: 
- [ ] deterministic signatures (ADR36)
- [ ] security / performance gain (design session?)

**Comment by noandrea** [comment]
As a countermeasure for abusing the verifiable credential we could implement some additional checks like limit the allowed size of the credential data

**Comment by noandrea** [comment]
we have collected the info, closing this
